### PR TITLE
EDA-2924 Modified Project Files

### PR DESCRIPTION
**Pull request by MustafaAbdaal**
Replaced old project files and added modified version, this time source files have been copied into the project directory by Raptor. 

Version: 1.1.62 - Aug 2024 RC2.

### CODE REVIEW

**Comment by ravikiranchollangi** [comment]
@MustafaAbdaal the CI is breaking. @NadeemYaseen do you the issue ?

**Comment by NadeemYaseen** [comment]
The CI is for Zaheer.  Mustafa is not a regular so recognition is failed and CI is fail.   Please ignore this failure.

**Comment by NadeemYaseen** [comment]
His fork is out of date. Please sync.

**Comment by ravikiranchollangi** [comment]
> His fork is out of date. Please sync.

@MustafaAbdaal please stay on top of your PRs.

**Pull request merged**
